# NOTE: location on Windows: C:\Users\<USERNAME>\AppData\Roaming\alacritty\alacritty.toml

[general]
import = [
    # Themes: https://github.com/alacritty/alacritty-theme
    #   git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
    "~/.config/alacritty/themes/themes/ayu_mirage.toml"
]

[font]
normal = { family = "NotoMono Nerd Font Mono", style = "Regular" }
#normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 15

[window]
title = "Alacritty" # This is the default static title
dynamic_title = true # This enables applications/shell to change the title
startup_mode = "Maximized"
padding = { x = 5, y = 5 }
#opacity = 0.8

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
bindings = [
    { mouse = "Right", action = "Paste" },
]

[terminal.shell]
program = "/usr/bin/bash"
args = ["--login"]

# for Windows
#program = "wsl"
#args = ["~"]
